# Default configurations for slot periods

fast:
  # offset  0   1   2   3   4   5   6   7   8   9   10  11  12  13   14   15
  slots:   [0,  0,  0,  0,  0,  4,  4,  4,  4,  6,  6,  6,  6,  6,  6,  8]
